'use client';

export function InstructionsStep() {
  return (
    <div className="iw-step-content">
      <h2 className="iw-step-title">Run the Repo Importer</h2>
      <p className="iw-step-subtitle">
        The import wizard turns an <code>architecture.review.yaml</code> file into a diagram. That
        file is generated by the <code>@arch-atlas/llm-importer</code> CLI, which correlates
        per-repository analysis artifacts &mdash; deterministically, with no model call of its own
        &mdash; into the connections between them. Run it locally first, then come back here to load
        the result.
      </p>

      <ol className="iw-instructions-list">
        <li>
          <strong>Produce a {'{repo}'}.analysis.json for each repository</strong>
          <p className="iw-step-hint">
            The importer core never talks to a model. Analyzing a repository is a separate step done
            by the <code>plugins/repo-analysis</code> skill/plugin &mdash; an <code>AGENTS.md</code>{' '}
            procedure that works with any coding agent (Claude Code, Cursor, Copilot, Codex,
            Windsurf, and more), against whatever model you&apos;ve configured that agent to use,
            local or hosted. See <code>plugins/repo-analysis/README.md</code> for setup.
          </p>
        </li>
        <li>
          <strong>Write a config file</strong>
          <p className="iw-step-hint">
            Create <code>import.yaml</code> pointing at your repositories and where the analysis
            artifacts and output should live:
          </p>
          <pre className="iw-code-block">
            {[
              "version: '2.0'",
              '',
              'output:',
              '  directory: ./architecture-output',
              '',
              'repositories:',
              '  - path: /path/to/service-a',
              '    name: Service A',
              '  - path: /path/to/service-b',
              '    name: Service B',
            ].join('\n')}
          </pre>
        </li>
        <li>
          <strong>Gather context, then analyze each repo</strong>
          <pre className="iw-code-block">
            {'pnpm --filter @arch-atlas/llm-importer run gather-context import.yaml'}
          </pre>
          <p className="iw-step-hint">
            Writes a bounded <code>{'{repo}'}.context.json</code> per repository (READMEs,
            manifests, a directory listing, a few relevance-ranked source files &mdash; secret files
            are never read). Point your coding agent at each bundle to produce the matching{' '}
            <code>{'{repo}'}.analysis.json</code> in <code>output.directory</code>.
          </p>
        </li>
        <li>
          <strong>Import</strong>
          <pre className="iw-code-block">
            {'pnpm --filter @arch-atlas/llm-importer run import import.yaml'}
          </pre>
          <p className="iw-step-hint">
            Correlates the analysis artifacts with deterministic cross-repository evidence passes
            &mdash; no model call, no network request.
          </p>
        </li>
        <li>
          <strong>Locate the review file</strong>
          <p className="iw-step-hint">
            The run writes <code>architecture.review.yaml</code> (and{' '}
            <code>architecture.arch.json</code>) to the <code>output.directory</code> from your
            config. The <code>.review.yaml</code> is the file you&apos;ll upload in the next step.
          </p>
        </li>
        <li>
          <strong>Continue below</strong>
          <p className="iw-step-hint">
            Click &ldquo;Next&rdquo; to load the review file and start classifying elements and
            reviewing connections.
          </p>
        </li>
      </ol>
    </div>
  );
}
