'use client';

export function InstructionsStep() {
  return (
    <div className="iw-step-content">
      <h2 className="iw-step-title">Run the Repo Importer</h2>
      <p className="iw-step-subtitle">
        The import wizard turns an <code>architecture.review.yaml</code> file into a diagram. That
        file is generated by the <code>@arch-atlas/llm-importer</code> CLI, which scans a folder of
        Git repositories &mdash; a bounded, deterministic context gather plus one structured
        local-model call per repository &mdash; then correlates the connections between them. Run it
        locally first, then come back here to load the result.
      </p>

      <ol className="iw-instructions-list">
        <li>
          <strong>Start a local model server</strong>
          <p className="iw-step-hint">
            The importer only ever calls a local, OpenAI-compatible endpoint &mdash; there is no
            hosted/cloud path. Run Ollama (<code>ollama serve</code>, model pulled) or an MLX-style
            server, and note its base URL (including <code>/v1</code>).
          </p>
        </li>
        <li>
          <strong>Write a config file</strong>
          <p className="iw-step-hint">
            Create <code>import.yaml</code> pointing at your model and your repositories:
          </p>
          <pre className="iw-code-block">
            {[
              "version: '2.0'",
              '',
              'localModel:',
              '  provider: ollama',
              '  endpoint: http://localhost:11434/v1',
              '  modelId: llama3',
              '',
              'output:',
              '  directory: ./architecture-output',
              '',
              'repositories:',
              '  - path: /path/to/service-a',
              '    name: Service A',
              '  - path: /path/to/service-b',
              '    name: Service B',
            ].join('\n')}
          </pre>
          <p className="iw-step-hint">
            No Python is required. Some local servers (e.g. oMLX) need an <code>apiKey</code> field
            under <code>localModel</code>.
          </p>
        </li>
        <li>
          <strong>Run it against your repos</strong>
          <pre className="iw-code-block">
            {'pnpm --filter @arch-atlas/llm-importer run import import.yaml'}
          </pre>
          <p className="iw-step-hint">
            Per repository it gathers a bounded context (READMEs, manifests, a directory listing, a
            few relevance-ranked source files &mdash; secret files are never read) and makes one
            structured model call, then runs deterministic cross-repository correlation.
          </p>
        </li>
        <li>
          <strong>Locate the review file</strong>
          <p className="iw-step-hint">
            The run writes <code>architecture.review.yaml</code> (and{' '}
            <code>architecture.arch.json</code>) to the <code>output.directory</code> from your
            config. The <code>.review.yaml</code> is the file you&apos;ll upload in the next step.
          </p>
        </li>
        <li>
          <strong>Continue below</strong>
          <p className="iw-step-hint">
            Click &ldquo;Next&rdquo; to load the review file and start classifying elements and
            reviewing connections.
          </p>
        </li>
      </ol>
    </div>
  );
}
